# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config

# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "rtnyfinalpwa"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. `public` and `graphql_public` schemas are included by default.
schemas = ["public", "graphql_public"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[api.tls]
# Enable HTTPS endpoints locally using a self-signed certificate.
enabled = false

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 17

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Configure one of the supported pooler modes: `transaction`, `session`.
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 20
# Maximum number of client connections allowed.
max_client_conn = 100

[db.vault]
secret_key = "env(SECRET_VALUE)"

[realtime]
enabled = true

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://127.0.0.1"
# OpenAI API Key to use for Supabase AI in the Supabase Studio.
openai_api_key = "env(OPENAI_API_KEY)"

[auth]
# The default URL that users are redirected to after signing in.
default_redirect_url = "http://localhost:3000/auth/callback"
# The default URL that users are redirected to after signing out.
default_signout_redirect_url = "http://localhost:3000/"
# The default URL that users are redirected to after signing up.
default_signup_redirect_url = "http://localhost:3000/auth/verify"
# The default URL that users are redirected to after resetting their password.
default_recovery_redirect_url = "http://localhost:3000/auth/verify"
# The default URL that users are redirected to after confirming their email.
default_email_confirm_redirect_url = "http://localhost:3000/auth/verify"
# The default URL that users are redirected to after changing their password.
default_update_redirect_url = "http://localhost:3000/auth/verify"
# The default URL that users are redirected to after verifying their email.
default_verify_redirect_url = "http://localhost:3000/auth/verify"
# The default URL that users are redirected to after confirming their email.
default_email_confirm_redirect_url = "http://localhost:3000/auth/verify"
# The default URL that users are redirected to after confirming their phone.
default_phone_confirm_redirect_url = "http://localhost:3000/auth/verify"
# The default URL that users are redirected to after confirming their phone.
default_phone_confirm_redirect_url = "http://localhost:3000/auth/verify"
# The default URL that users are redirected to after confirming their phone.
default_phone_confirm_redirect_url = "http://localhost:3000/auth/verify"
# Passwords shorter than this value will be rejected as weak. Minimum 6, recommended 8 or more.
minimum_password_length = 6
# Passwords that do not meet the following requirements will be rejected as weak. Supported values
# are: `letters_digits`, `lower_upper_letters_digits`, `lower_upper_letters_digits_symbols`
password_requirements = ""
